
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-cpp:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Prepare System
      run: |
        zypper --non-interactive in --no-recommends \
          python3 \
          python3-setuptools

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Package Build
      run:  yast-ci-cpp
